## 0. 넘파이 알아보기

In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.6'

## 0-1 다차원 배열 만들기 

### 넘파이 1차원 배열을 만들고 출력하기

In [2]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)

[1 2 3 4 5]


### 넘파이 배열을 특정 범위에 딸라 만들고 출력하기 

In [4]:
my_range_array = np.arange(0, 10, 2)

print(my_range_array)

[0 2 4 6 8]


## 0-2 다차원 배열을 만들기

In [5]:
my_range_array = np.arange(0, 20).reshape(10,2)

print(my_range_array)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [6]:
my_range_array.shape

(10, 2)

## 0-3 랜덤모듈로 다차원 배열 만들기

In [7]:
my_random_array = np.random.rand(2, 3)

print(my_random_array)

[[0.97998995 0.88823071 0.08644083]
 [0.40591931 0.50055669 0.77386205]]


In [8]:
my_random_array.shape

(2, 3)

# 1.  판다스 기본 알아보기

- 판다스 모듈은 행과 열로 구성된 2차원 배열의 형태를 잘 처리할 수 있는 모듈
- 2차원 배열을 데이터프레임으로 만들어서 관리
- 이 데이터프레임은 엑셀의 시트, 데이터베이스의 테이블 과 같은 구조이다. 

## 1-1 판다스 기본 개념 

-  판다스 모듈을 사용하기 위해서는 import 해야한다.
- 보통 판다스 모듈은 별칭 pd를 지정해서 사용한다.
- 판다스 모듈의 버전을 꼭 확인해본다. 

### 판다스 모듈의 별칭을 pd로 정하기

In [3]:
import pandas as pd

### 판다스 모듈의 버전을 확인하기

In [11]:
pd.__version__

'1.5.3'

## 주요 클래스 : 

- 판다스 모듈을 처리하기 위한 데이터 구조는 2차원은 데이터프레임, 1차원은 시리즈이다. 
- 이 두 가지를 모두 클래스로 지원한다.  

## 데이터프레임

![](../image/데이터프레임.png)

In [12]:
pd.DataFrame

pandas.core.frame.DataFrame

## 시리즈

![](../image/시리즈.png)

In [13]:
pd.Series

pandas.core.series.Series

## 다차원 배열을 넣고 데이터프레임 생성하기 

In [14]:
df_ = pd.DataFrame(my_random_array, columns=list("abc"))

In [15]:
df_

a         b         c
0  0.979990  0.888231  0.086441
1  0.405919  0.500557  0.773862

## 데이터프레임의 스키마 정보 

- 칼럼정보 : columns
- 행정보   : index
- 데이터프레임의 형태 : shape
- 데이터프레임의 값 : values

In [18]:
df_.columns

Index(['a', 'b', 'c'], dtype='object')

In [19]:
df_.index

RangeIndex(start=0, stop=2, step=1)

In [20]:
df_.shape

(2, 3)

### 데이터프레임의 값은 넘파이 다차원 배열로 관리

In [17]:
df_.values

array([[0.97998995, 0.88823071, 0.08644083],
       [0.40591931, 0.50055669, 0.77386205]])

## 1-2  CSV 파일 읽고 기본 정보 확인하기  

- 판다스 모듈에서 csv 확장자 파일을 읽으면 바로  데이터프레임 객체로 변환한다.
- 위에서 배운 것처럼 다차원 배열에 값을 저장하고 스키마 정보에 따라서 데이터프레임을 처리해 준다.

### 파일 위치를 지정하기 

-  자주 사용하려면 특정 파일의 경로를 지정한다. 

In [21]:
path = "../data/train.csv"

###  csv 파일을 읽는 read_csv 함수 기능 확인하기 

- 함수, 클래스, 메서드 등의 기능에 대한 설명을 help로 확인할 수 있다. 


In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_li

### read_csv 함수로 파일 읽기

- csv 파일을 값을 쉼표로 구분해서 처리
- 보통 엑셀 파일을 csv로 변환해서 처리한다.
- 파일을 읽으면 데이터프레임으로 변수 이름을 df로 시작해서 지정한다. 

In [22]:
df = pd.read_csv(path)

In [25]:
type(df)

pandas.core.frame.DataFrame

### 데이터프레임 데이터를 앞과 뒤부분 정보확인

- head, tail 메서드로 앞과 뒤의 데이터를 확인한다

In [23]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [24]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

## 1-3 데이터프레임의 구성정보 확인하기

- 데이터의 구성정보인 모양, 칼럼, 인덱스 등을 확인한다. 

### 데이터프레임의 차원을 확인

In [26]:
df.shape

(891, 12)

### 데이터프레임의 칼럼정보를 확인하기 

In [27]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### 데이터프레임의 행정보 확인하기 

In [28]:
df.index

RangeIndex(start=0, stop=891, step=1)

### 데이터프레임 칼럼의 데이터 타입을 확인하기

- int/float 은 정수와 실수 
- 처음 파일을 읽으면 int64/float64로 처리 => 실제 8/16/32/64 를 제공해서 타입을 바꿀 수 있다. 
- object 타입은 파이썬에서 제공하는 타입을 사용한다. (예를들면 str 인 문자열을 판다스에서는 object로 인식)

In [34]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### 데이터프레임의 기본 정보 확인하기 

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# 2. 데이터프레임 세부  데이터 확인 

## 2-1 하나의 칼럼을 조회하고 값을 확인

In [14]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### 하나의 칼럼을 조회하기 

- 하나의 칼럼을 문자열로 인덱스 검색하면 1차원의 시리즈 객체로 확인가능하다. 

In [30]:
ser1 = df['Pclass']

In [31]:
type(ser1)

pandas.core.series.Series

### 일부 시리즈 원소만 확인하기 

In [32]:
ser1.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [33]:
ser1.tail()

886    2
887    1
888    3
889    1
890    3
Name: Pclass, dtype: int64

### 시리즈 내부의 자료형 확인하기 
- 시리즈는 하나의 자료형으로만 구성한다. 

In [18]:
ser1.dtype

dtype('int64')

## 2-2 시리즈 내부의 유일한 값을 확인

- unique 메서드로 몇개의 값으로 구성했는지 확인
- value_counts 메서드로 각 유일한 값의 개수를 확인 

### 분류된 값의 개수 

In [35]:
ser1.nunique()

3

### 분류된 실제 값 확인 

In [36]:
ser1.unique()

array([3, 1, 2])

### 분류된 값의 분포를 확인 

In [37]:
ser1.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

## 2-3 데이터프레임의 칼럼으로 값을 조회하기

- 데이터프레임의 특징은 칼럼별로 처리하는 기준이다.
- 그래서 대부분을 칼럼으로 검색해서 처리한다. 

### 인덱스 검색 내에 칼럼이름을 리스트로 전달

- 칼럼이름으로 전달하면 칼럼 별로 조회가 된다. 
- 칼럼 단위로 조회하면 데이터프레임으로 출력한다. 

In [39]:
type(df[['Pclass']])

pandas.core.frame.DataFrame

In [38]:
df[['Pclass']].head()

Pclass
0       3
1       1
2       3
3       1
4       3

### 여러 칼럼을 조회하기

- 칼럼을 리스트에 요소로 나열해서 조회한다. 

In [40]:
df[['PassengerId', 'Survived', 'Pclass', 'Name']].head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                             Heikkinen, Miss. Laina  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                           Allen, Mr. William Henry

## 2-3 데이터프레임의 자료형으로 칼럼을 조회하기

-  select_dtypes 메서드를 사용해서 특정 자료형을 선택해서 칼럼을 조회하기
-  매개변수 include는 포함되는 자료형 exclude 매개변수는 포함하지 않는 자료형을 지정

### 칼럼명을 한글로 변환하기 

- 대부분 영문이므로 이에 해당하는 한글명을 작성한다.
- columns 속성은 동일한 사이즈의 리스트와 대체가 가능하지만 내부의 원소를 변경할 수 없다.

In [42]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [45]:
cols =['승객번호','생존여부','승객등급','이름','성별','나이','가족탑승',
      '파치', '티켓', '운임', '객실', '탑승']

In [46]:
df.columns = cols

### 숫자 자료형만 확인한다

- 특정 자료형의 칼럼을 처리 : select_dtypes 
- include는 number(int, float), object
- 또는 exclude를 지정해서 그외 자료형만 추출

In [47]:
df.select_dtypes(include="number")

승객번호  생존여부  승객등급    나이  가족탑승  파치       운임
0       1     0     3  22.0     1   0   7.2500
1       2     1     1  38.0     1   0  71.2833
2       3     1     3  26.0     0   0   7.9250
3       4     1     1  35.0     1   0  53.1000
4       5     0     3  35.0     0   0   8.0500
..    ...   ...   ...   ...   ...  ..      ...
886   887     0     2  27.0     0   0  13.0000
887   888     1     1  19.0     0   0  30.0000
888   889     0     3   NaN     1   2  23.4500
889   890     1     1  26.0     0   0  30.0000
890   891     0     3  32.0     0   0   7.7500

[891 rows x 7 columns]

### 숫자자료형만 조회되었는지 확인한다. 

In [48]:
df.select_dtypes(include="number").dtypes

승객번호      int64
생존여부      int64
승객등급      int64
나이      float64
가족탑승      int64
파치        int64
운임      float64
dtype: object

### 숫자를 제외한 칼럼만 조회하기 

In [49]:
df.select_dtypes(exclude="number")

이름      성별  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

                   티켓    객실 탑승  
0           A/5 21171   NaN  S  
1            PC 17599   C85  C  
2    STON/O2. 3101282   NaN  S  
3              113803  C123  S  
4              373450   NaN  S  
..                ...   ... ..  
886            211536   NaN  S  
887            112053   B42  S  
888        W./C. 6607   NaN  S  
889            111369  C148  C  
890            370376   NaN  Q  

[891 rows x 5 columns]

### 판다스에서 파이썬 자료형은 전부 object 타입으로 인식한다.

-  보통 이 object 자료형은 대부분 문자열로 처리된다

In [50]:
df.select_dtypes(exclude="number").dtypes

이름    object
성별    object
티켓    object
객실    object
탑승    object
dtype: object

## 2-4 데이터프레임의 칼럼을 이름으로 조회하기

- filter 메서드의 like를 사용해서 칼럼의 이름을 조회

### 특정한 문자를 지정하면 해당 칼럼을 조호한다

In [52]:
df.filter(like="승")

승객번호  승객등급  가족탑승 탑승
0       1     3     1  S
1       2     1     1  C
2       3     3     0  S
3       4     1     1  S
4       5     3     0  S
..    ...   ...   ... ..
886   887     2     0  S
887   888     1     0  S
888   889     3     1  S
889   890     1     0  C
890   891     3     0  Q

[891 rows x 4 columns]

### 특정 단어가 들어있는 여러 칼럼을 조회하기 

In [53]:
df.filter(like="이")

이름    나이
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

## 2-3. 판다스 행별 데이터 확인 

- 데이터프레임은 보통 칼럼 기준으로 검색한다.
- 데이터프레임을 행기준으로 처리하려면 loc, iloc라는 별도의 인덱서 객체를 사용해야한다.
- loc는 인덱스의 이름으로 조회한다.
- iloc는 인덱스의 값으로 조회한다. 


## 2-3-1 인덱스의 이름으로 조회하기

- loc 인덱서는 행과 열의 인덱스의 이름으로 조회한다.
- 보통 인덱스는 숫자이고 칼럼은 문자이다.


## 인덱스 처리 간단한 예제 알아보기 

In [8]:
df_test = pd.DataFrame([[2, 3], [5, 6], [8, 9]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])
df_test

max_speed  shield
cobra               2       3
viper               5       6
sidewinder          8       9

##  인덱스 이름으로 행에 대해서만 읽기
![](../image/loc처리2.png)

In [9]:
df_test.loc['viper']

max_speed    5
shield       6
Name: viper, dtype: int64

In [10]:
df_test.loc[['viper','sidewinder']]

max_speed  shield
viper               5       6
sidewinder          8       9

## loc 인덱서에서 연산자  처리

![](../image/loc처리1.png)

In [13]:
df_test.loc[df_test['shield'] > 6]

max_speed  shield
sidewinder          8       9

### 인덱스 정보에 따른 행을 조회하기

- loc 객체를 사용한다.
- 이때 인덱스 검색에 첫번째는 행의 정보, 두번째는 칼렴이름을 사용 ]

In [54]:
df.select_dtypes(include="number").columns

Index(['승객번호', '생존여부', '승객등급', '나이', '가족탑승', '파치', '운임'], dtype='object')

In [55]:
df.loc[1:100,df.select_dtypes(include="number").columns]

승객번호  생존여부  승객등급    나이  가족탑승  파치       운임
1       2     1     1  38.0     1   0  71.2833
2       3     1     3  26.0     0   0   7.9250
3       4     1     1  35.0     1   0  53.1000
4       5     0     3  35.0     0   0   8.0500
5       6     0     3   NaN     0   0   8.4583
..    ...   ...   ...   ...   ...  ..      ...
96     97     0     1  71.0     0   0  34.6542
97     98     1     1  23.0     0   1  63.3583
98     99     1     2  34.0     0   1  23.0000
99    100     0     2  34.0     1   0  26.0000
100   101     0     3  28.0     0   0   7.8958

[100 rows x 7 columns]

## 2-3-2 인덱스의 숫자 정보로 처리하기

- 데이터프레임은 내부적으로는 행과 열의 인덱스가 숫자로 지정되어있다.
- 보통 데이터프레임의 행의 인덱스는 숫자이지면 내부적으로는 별도의 기본 인덱스가 지정되어 있다. 

### 행과 열의 인덱스로 지정해서 읽기
- 칼럼은 2번째 3번째 4번째 칼럼을 지정해서 읽는다

In [56]:
df.iloc[:100,[1,2,3]]

생존여부  승객등급                                                 이름
0      0     3                            Braund, Mr. Owen Harris
1      1     1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2      1     3                             Heikkinen, Miss. Laina
3      1     1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      0     3                           Allen, Mr. William Henry
..   ...   ...                                                ...
95     0     3                        Shorney, Mr. Charles Joseph
96     0     1                          Goldschmidt, Mr. George B
97     1     1                    Greenfield, Mr. William Bertram
98     1     2               Doling, Mrs. John T (Ada Julia Bone)
99     0     2                                  Kantor, Mr. Sinai

[100 rows x 3 columns]

### 특정 칼럼을 읽기위해 컴프리헨션을 사용

- 칼럼의 인덱스가 짝수인 경우만 조회

In [57]:
ss = [i for i,_ in enumerate(df.columns) if i %2 ==0]

In [58]:
df.iloc[:100,ss]

승객번호  승객등급      성별  가족탑승                티켓       객실
0      1     3    male     1         A/5 21171      NaN
1      2     1  female     1          PC 17599      C85
2      3     3  female     0  STON/O2. 3101282      NaN
3      4     1  female     1            113803     C123
4      5     3    male     0            373450      NaN
..   ...   ...     ...   ...               ...      ...
95    96     3    male     0            374910      NaN
96    97     1    male     0          PC 17754       A5
97    98     1    male     0          PC 17759  D10 D12
98    99     2  female     0            231919      NaN
99   100     2    male     1            244367      NaN

[100 rows x 6 columns]

# 3.   판다스 전체 데이터 확인 : 통계 

- 데이터의 기술통계 값을 확인할 수 있는 메소드들을 확인한다.  

## 3-1 숫자값에 대한 통계 정보 확인

### 숫자 칼럼 가져오기 

In [59]:
df_num = df.select_dtypes(include="number")

### 최대값과 최소값 확인하기 

In [60]:
df_num.max()

승객번호    891.0000
생존여부      1.0000
승객등급      3.0000
나이       80.0000
가족탑승      8.0000
파치        6.0000
운임      512.3292
dtype: float64

In [61]:
df_num.min()

승객번호    1.00
생존여부    0.00
승객등급    1.00
나이      0.42
가족탑승    0.00
파치      0.00
운임      0.00
dtype: float64

### 평균값과 중앙값 가져오기 

In [62]:
df_num.mean()

승객번호    446.000000
생존여부      0.383838
승객등급      2.308642
나이       29.699118
가족탑승      0.523008
파치        0.381594
운임       32.204208
dtype: float64

In [63]:
df_num.median()

승객번호    446.0000
생존여부      0.0000
승객등급      3.0000
나이       28.0000
가족탑승      0.0000
파치        0.0000
운임       14.4542
dtype: float64

### 분포에 대한 데이터 가져오기 

In [64]:
df_num.quantile([0.25,0.5,0.75])

승객번호  생존여부  승객등급      나이  가족탑승   파치       운임
0.25  223.5   0.0   2.0  20.125   0.0  0.0   7.9104
0.50  446.0   0.0   3.0  28.000   0.0  0.0  14.4542
0.75  668.5   1.0   3.0  38.000   1.0  0.0  31.0000

### 분산 및 표준편차 처리하기 

In [65]:
df_num.var()

승객번호    66231.000000
생존여부        0.236772
승객등급        0.699015
나이        211.019125
가족탑승        1.216043
파치          0.649728
운임       2469.436846
dtype: float64

In [66]:
df_num.std()

승객번호    257.353842
생존여부      0.486592
승객등급      0.836071
나이       14.526497
가족탑승      1.102743
파치        0.806057
운임       49.693429
dtype: float64

### 전체 요약통계 처리하기 

In [67]:
df_num.describe()

승객번호        생존여부        승객등급          나이        가족탑승          파치  \
count  891.000000  891.000000  891.000000  714.000000  891.000000  891.000000   
mean   446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   
std    257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   
min      1.000000    0.000000    1.000000    0.420000    0.000000    0.000000   
25%    223.500000    0.000000    2.000000   20.125000    0.000000    0.000000   
50%    446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   
75%    668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   
max    891.000000    1.000000    3.000000   80.000000    8.000000    6.000000   

               운임  
count  891.000000  
mean    32.204208  
std     49.693429  
min      0.000000  
25%      7.910400  
50%     14.454200  
75%     31.000000  
max    512.329200

### 칼럼이 많은 경우는 전치해서 요약통계 확인하기 

In [68]:
df_num.describe().T

count        mean         std   min       25%       50%    75%       max
승객번호  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5  891.0000
생존여부  891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0    1.0000
승객등급  891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0    3.0000
나이    714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   80.0000
가족탑승  891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0    8.0000
파치    891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0    6.0000
운임    891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0  512.3292

## 3-2 범주값에 대한 통계 확인

### 문자열 칼럼값만 가져오기 

In [69]:
df_obj = df.select_dtypes(exclude="number")

### 데이터 확인하기 

In [70]:
df_obj.head()

이름      성별  \
0                            Braund, Mr. Owen Harris    male   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                             Heikkinen, Miss. Laina  female   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                           Allen, Mr. William Henry    male   

                 티켓    객실 탑승  
0         A/5 21171   NaN  S  
1          PC 17599   C85  C  
2  STON/O2. 3101282   NaN  S  
3            113803  C123  S  
4            373450   NaN  S

### 개수 확인하기 

In [71]:
df_obj.count()

이름    891
성별    891
티켓    891
객실    204
탑승    889
dtype: int64

### 각 칼럼의 유니크 값 확인하기 

In [72]:
df_obj.nunique()

이름    891
성별      2
티켓    681
객실    147
탑승      3
dtype: int64

### 요약통계 확인하기 

In [73]:
df_obj.describe()

이름    성별      티켓       객실   탑승
count                       891   891     891      204  889
unique                      891     2     681      147    3
top     Braund, Mr. Owen Harris  male  347082  B96 B98    S
freq                          1   577       7        4  644